# .mega-linter.yml
# Documentation: https://nvuillam.github.io/mega-linter/

# The configuration of the linters that you want to use
linters:
  # Python linting configuration
  black:
    enabled: true
    # The version of black you want to use
    version: "23.1.0" # specify the version you need
  flake8:
    enabled: true
    # The version of flake8 you want to use
    version: "6.0.0" # specify the version you need

# Optional: Customize the way MegaLinter works
# For instance, you might want to specify the file types to lint
files:
  python: "*.py"

# You can also configure how reports and other settings are handled
# For example:
reporters:
  - console

