# .github/workflows/linter.yml

name: Code Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use the latest LTS version or as needed

    - name: Run MegaLinter
      run: npx mega-linter --install && npx mega-linter

