name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run MegaLinter
      run: docker run --rm -v $(pwd):/tmp/lint oxsecurity/megalinter-python:v8.0.0

